### ISSUE TITLE
Dashboard feature Downloads (last 6 months)

### ISSUE THREAD

**Issue by harvex** [FraserCoyle/sermon-manager-issues#115]
This feature currently displays as:

Downloads (last 6 months)[["Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],["0","0","0","0","0","0","0","0","0","0","0","96","68"]]

I assume this is a work in progress.

**Comment by andrewmfraser** [comment]
This is fixed, nice graphs are appearing now :+1:
