### ISSUE TITLE
UI Update v1.0.0

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#119]
Please use this issue to track the UI update and add missing tasks.

# Pages
- [x] Design new registration process (Mike)
- [ ] Design confirm page (Mike)
- [ ] Redesign steps 1+2 to be step 1 (Mike)
- [ ] Design Email template (Mike)
- [x] Design Registration Page (Mike)
- [ ] Design Error pages v1_error_404 & v1_error_500 (Mike)
- [ ] Design Bandwidth Limit Reached Error Page v1_error_bandwidth (Mike)
- [ ] Build Base Template v1_template (Jonah)
- [ ] Build v1_login (Jonah)
- [ ] Build v1_registration (Jonah)
- [ ] Build v1_analytics_main (Jonah)
- [ ] Build v1_sermons_view (Jonah)
- [ ] Build v1_sermons_add (Jonah)
- [ ] Build v1_sermons_edit (Jonah)
- [ ] Build v1_series_view (Jonah)
- [ ] Build v1_series_add (Jonah)
- [ ] Build v1_series_edit (Jonah)
- [ ] Build v1_speakers_view (Jonah)
- [ ] Build v1_speakers_add (Jonah)
- [ ] Build v1_speakers_edit (Jonah)
- [ ] Build v1_topics_view (Jonah)
- [ ] Build v1_settings_profile (Jonah)
- [ ] Build v1_settings_branding (Jonah)
- [ ] Build v1_settings_integrations (Jonah)
- [ ] Build v1_settings_subscription (Jonah)
- [ ] Build v1_settings_users (Jonah)
- [ ] Build v1_settings_roles_add (Jonah)
- [ ] Build v1_settings_roles_edit (Jonah)
- [ ] Build v1_settings_manage_plan (Jonah)
- [ ] Build v1_admin_churches (Jonah)
- [ ] Build v1_admin_analytics (Jonah)
- [ ] Build v1_admin_plans (Jonah)
- [ ] Build v1_admin_roles (Jonah)
- [ ] Build v1_admin_permissions (Jonah)
- [ ] Build v1_admin_registrations (Jonah)
- [ ] Build v1_admin_sessions (Jonah)
- [ ] Build v1_admin_logs (Jonah)
- [ ] Build v1_error_404 (Jonah)
- [ ] Build v1_error_500 (Jonah)
- [ ] Build v1_error_bandwidth (Jonah)

# UI/UX Improvements
- [ ] Autocomplete the series part number on selection of series in v1_sermons_add
- [ ] Show if a file is processing on v1_sermons_view and v1_sermons_edit
- [ ] Form Feedback, Accessibility, Tab Index, Error Handling

**Comment by jonahm** [comment]
https://css-tricks.com/almanac/selectors/p/placeholder-shown/
