### ISSUE TITLE
[UI] Monthly vs Annual radio buttons - no styling

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#129]
This issue exists in registration and in Upgrade Plan
<img width="214" alt="screenshot 2016-04-22 23 03 57" src="https://cloud.githubusercontent.com/assets/231299/14756059/a393eb22-08de-11e6-8840-a89bc9298b0c.png">

**Comment by jonahm** [comment]
@JNaismith Are you able to implement the switch I made earlier? Thanks. 

According to Mike, Annual needs to display as default. (on/off)

Next to the Annual element please put `<span class="req">Annual Billing 10&#37;</span>` 

`&#37;` is %
