### ISSUE TITLE
[UI] Search

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#158]
- [x] Only show results bar when there are results
<img width="1427" alt="screenshot 2016-04-24 09 10 58" src="https://cloud.githubusercontent.com/assets/231299/14766315/8d4d9b50-09fc-11e6-9f21-e3819de17660.png">
- [x] Add auto focus - when a user clicks search the search box should focus
Use the following code in the Javascript method:
`$('#search-button').click(function(){$('#search').focus();});`
- [x] Hitting the enter key doesn't show the first result
- [x] No UI feedback if no results from your search
- [x] Search hotkey (hit s) no longer works

**Comment by jonahm** [comment]
<img src="https://i.imgur.com/bHKg9TG.png">

**Comment by jonahm** [comment]
The auto focus code doesn't work on this form

**Comment by andrewmfraser** [comment]
Why not? is there something wrong with the function, did you wrap it in document ready?

**Comment by jonahm** [comment]
We managed to use `autofocus` as a HTML attribute. Works just fine.
