### ISSUE TITLE
[UI] Text Wrapping in Sermon Results Table

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#159]
Let's allow text wrapping on Sermon Name and Series Name but the other fields should be set to no-wrap:
<img width="1394" alt="screenshot 2016-04-24 09 20 24" src="https://cloud.githubusercontent.com/assets/231299/14766352/d710fa7e-09fd-11e6-8b7c-0d305b66977a.png">

**Comment by jonahm** [comment]
@JNaismith Are you able to implement this class `.no-wrap` to the sermon name & series name? Is there a dynamic way to do that?
