### ISSUE TITLE
[UI] Registration Pages

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#162]
- [x] Massive gap bellow contact us (page height is wrong)
- [x] Can't click next even though required fields are filled
- [x] Spacing between annual vs monthly billing switcher and back/next buttons incorrect
- [x] Card Number, Expiry Month and Expiry Date field red even though I haven't attempted to fill it in
- [x] Random text on finish page
- [x] Error Text wrong colour
- [x] Typing a card number with spaces doesn't let you type the whole card number
- [x] Upon completing registration I got a white screen
- [x] Registration throwing error "There are some errors in the information you gave. Please try again." - no indication what the error actually is
- [x] tabbing doesn't work properly
- [x] On displaying an error the registration page disappears to the left and leaves a gap on the right
- [x] Next buttons should be disabled until all fields on that tab are filled
- [x] Back button on details tab doesn't do anything
- [x] Required field asterisk only exists on Full Name
- [x] Auto create subdomain no longer works
- [x] Cursor type on hover over plans should be pointer
- [x] Cursor type incorrect on contact us links
- [x] Extra horizontal scrollbars are appearing
- [x] Large gap below footer
- [x] Billing Form is incorrectly stacked
- [x] Clicking Edit on the Finish page next to any of the headings takes you to the login page
- [x] Complete Registration button shouldn't be active until all form fields are filled
- [x] Finish page is showing a VISA icon even though no card details are entered
- [x] Registration into page is incorrectly spaced
- [x] Logos not linked

**Comment by jonahm** [comment]
Andrew, pls can you confirm/reproduce what you mean by the register page disappearing left? Jon/I couldn't reproduce.

**Comment by andrewmfraser** [comment]
Looks like that issue is fixed already

**Comment by andrewmfraser** [comment]
Test Data I used for Registration:
Andrew Fraser
fraser.andrew@gmail.com
Grace Church Leith
grace-church-leith
www.grace-church-leith.com
Somewhere in Leith
Shouldn't need to fill this in
Edinburgh - this field keeps changing to a number
EH10 1PW
Hello
Core Plan - Annual
4242424242424242
06 
2017
123
NULL for promotion field
