### ISSUE TITLE
[UI] Add Sermon page

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#167]
- [x] Add Series appears under "Part:" after selecting a series
- [x] Time/Date Icon Buttons do nothing
- [x] DatePicker Styling missing - scroll bar appearing, left arrow over the year, looks out of place
- [x] Passages - shows empty box to start
- [x] Passages - can only click on the actual text rather than the whole "button"
- [x] Passages - shouldn't be able to select end verse earlier than start verse
- [x] Passages - you can't select cross-chapter passages
- [x] Video - if you click attach without putting in a url it displays invalid URL in the modal and then displays the x next to the url field even though no url is there
- [x] Image preview rotated picture?
- [x] Audio and Image didn't upload

**Comment by jonahm** [comment]
Image upload is possible? https://i.imgur.com/Id3IfQh.png
