### ISSUE TITLE
[UI] Login

### ISSUE THREAD

**Issue by michaeljohncoyle** [FraserCoyle/sermon-manager-issues#177]
Missing a line under the logo see images below:

![sermonmanager-backend-tablet-login](https://cloud.githubusercontent.com/assets/19221166/15070649/6ffb6340-137d-11e6-857a-ba9c215c0ec8.jpg)
![screen shot 2016-05-06 at 10 52 17](https://cloud.githubusercontent.com/assets/19221166/15070637/5bd11a22-137d-11e6-8a64-0d464289e680.png)

**Comment by jonahm** [comment]
Applied: https://i.imgur.com/7FmXdAO.png
