### ISSUE TITLE
Change Card Details

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#178]
When showing the previous attached card, can we not show this in a form but instead with the card badge on a single line. No expiry date either. The last 4 digits of the card should be enough for a user to figure out which card it is. Also if the person viewing the page is not the card holder they should see that another user has the card attached.

E.g. if Mike views Destiny and I am the card holder the card details tab should say Andrew's Card instead of the last 4 digits with the card icon. Any user with billing permissions should still be able to update the card, this allows the person who is paying to be switched easily.

**Comment by andrewmfraser** [comment]
@michaeljohncoyle can you do some design work around this?

**Comment by michaeljohncoyle** [comment]
Hows this? Trying to move away from distracting coloured buttons in the main body as well. 

**Admin View**
![screen shot 2016-05-10 at 09 56 14](https://cloud.githubusercontent.com/assets/19221166/15140964/90130190-1695-11e6-932a-e29d7babc66b.png)

**Sermon Uploader View**
![screen shot 2016-05-10 at 10 02 24](https://cloud.githubusercontent.com/assets/19221166/15141086/54e47f1c-1696-11e6-901a-20af0ddd3dcf.png)

**Comment by andrewmfraser** [comment]
Looks like this is complete can I close this issue?

**Comment by jonahm** [comment]
Yup working well: https://i.imgur.com/5HqBxzh.png
