### ISSUE TITLE
For Admins: Switch Church using the search box

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#187]
Would be really good if we could switch church from the search bar.

@michaeljohncoyle can you produce a church icon for search results?

**Comment by michaeljohncoyle** [comment]
Hows this? 

The icon is in cuts > backend > navigation > church-icon-36

![screen shot 2016-05-19 at 10 24 46](https://cloud.githubusercontent.com/assets/19221166/15388935/57250888-1dac-11e6-9e26-204588665184.png)
