### ISSUE TITLE
SM Registration trying to use the wrong plan ID with stripe

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#189]
ERROR - 2016-05-23 17:31:30 --> Severity: error --> Exception: No such plan: lit /var/www/dashboard.sermonmanager.net/application/libraries/Stripe/Stripe/ApiRequestor.php 142

Actual Plan Name: lite-plan-annual

**Comment by JNaismith** [comment]
This has been sorted. For some reason, the live version of the database only stored plan IDs as 3 characters. This has been extended and the database has been updated with the IDs as stated on Stripe.
