### ISSUE TITLE
Add View Portal Button to Analytics Page

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#204]

**Comment by JNaismith** [comment]
I'm not sure what you mean by a view portal button.

**Comment by andrewmfraser** [comment]
There's no way to go to their frontend library from the Dashboard

**Comment by michaeljohncoyle** [comment]
I originally had 'view buttons' on some of the pages. Want to add one to just the analytics page?

![screen shot 2016-06-02 at 09 55 39](https://cloud.githubusercontent.com/assets/19221166/15739501/35b2878c-28a8-11e6-91d8-5e74056916d7.png)

**Comment by andrewmfraser** [comment]
View Portal on the Analytics Page
View Sermon on each Sermon Edit Page

**Comment by andrewmfraser** [comment]
Sorry should be View Library
