### ISSUE TITLE
Series Pagination not working

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#49]

**Comment by thealioli** [comment]
Does this refer to the front end/public view?
We noticed that clicking on the series name in this view take the user to the sermon itslelf rather than all the sermons in the series, which would make more sense?
If this refers to something else, will add a separate request for the above!

**Comment by andrewmfraser** [comment]
All issues have a label either sm-dashboard or sm-frontend this one is Dashboard.

Yeah the link doesn't work because filtering hasn't been implemented yet, so please create a new issue so we remember to change the link and reference #6 by putting the hastag and 6 in your comment :)
