### ISSUE TITLE
Improve Passages Input

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#58]
From Dena (St C's): When you try to edit a sermon, you can’t edit the scripture references. you can only delete it (and that just by clicking on it which is a bit confusing in my opinion, since who wouldn’t try just clicking on something to access it for changing).

**Comment by andrewmfraser** [comment]
Probably going to move this to a smart text box where you can just enter the passages in a comma separated value list, unless you have a better idea of how we should input them?

We can handle cross-chapter passages but the current form doesn't allow it as well so this is definitely on the list to sort.

**Comment by thealioli** [comment]
I actually really liked the way the old one worked as it made perfect sense :)

Would be good to have confirmation in there somewhere that it does handle cross chapter references, although I'm sure you don't want to be filling the interface with explanatory text.

Maybe having the 'end' verse pre-filled (greyed out) with 'end' to show that this auto feature works?

I'll have a think and get back to this if I have any inspiration...
