### ISSUE TITLE
Do series part numbers auto assign

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#59]
In the previous version of Sermon Manager, the interface confirmed that part numbers in a series were automatically assigned (and stated so). Unless a particular number was to be assigned.

Do part numbers still do this? If so, it would be good for the interface to confirm this as a sanity check!

**Comment by andrewmfraser** [comment]
They do, how about when you click a series it goes and fetches the latest series number and shows it greyed out in the box?

In the meantime we will just add text to say it's auto-generated like before.

**Comment by thealioli** [comment]
Yeah, that sound ideal!

**Comment by andrewmfraser** [comment]
Complete will be rolled out with UI1.0
