### ISSUE TITLE
'Add New' etc style

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#60]
Not sure if this is the best place to report this, but the style of the pages to add new sermon is not very easy on the eyes!

The grey borders are just a little too pale I feel and it's quite annoying to work out what is going on in the page sometimes. 

Some of this will be down to familiarity, but I'm finding that I'm have to squint my eyes a little too much which is a little frustrating.

**Comment by andrewmfraser** [comment]
This will be sorted in the UI Update: #33

**Comment by andrewmfraser** [comment]
Superseded by #119
