### ISSUE TITLE
Unpublishing a sermon?

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#61]
Sometimes we have to unpublish a sermon for a variety of reasons, but it's not that clear on the interface how to go about this? We worked out that hitting delete after selecting the date and time boxes would clear them and then updating the sermon. 

Date and time selection grids appear when re-selecting these boxes - which makes sense for editing the information, but not deleting. Maybe have an 'un-publish' button to avoid this confusion (because the calendar and time grids re-appearing does make sense and obviously needs to be kept!)

**Comment by andrewmfraser** [comment]
We will add an Unpublish button which removes the date and time :+1:
