### ISSUE TITLE
Bug with video preview in sermon page?

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#62]
When adding a new sermon and attaching a YouTube link, it pulls through the video as a preview. However, when re-accessing the sermon, after publication for example, where the video preview was is just 'Attach Video' and a cross to delete it.

When the cross is hit, the video un-attaches and the box reappears to add a new link, but it's a little confusing to know what's going on.

**Comment by andrewmfraser** [comment]
We should change the design of this, is it the wording that's confusing or the fact you can still see the link. E.g. should we change the title to Video and instead of showing the link and a cross show a button that says Remove or Remove Video?

**Comment by thealioli** [comment]
It's not even that it's confusing, it doesn't seem to be working properly? i.e. it doesn't show the link.

I'd say leave the preview box in (maybe make it smaller though) and change the wording above to 'Remove Sermon' and a cross as you suggest :)

**Comment by andrewmfraser** [comment]
Can you screenshot it and list:
* Operating System
* Browser and Version (check about menu)

**Comment by thealioli** [comment]
Windows 7 Enterprise
Chrome 44 (but also doing it in Chrome 43)
![semon manager video pic 1](https://cloud.githubusercontent.com/assets/8791163/7813396/97c097d2-03b2-11e5-9451-4d15ba342f73.JPG)

**Comment by andrewmfraser** [comment]
@thealioli is this still happening since we updated to use YouTube API v3?

**Comment by thealioli** [comment]
Yeah, unfortunately still happening!
