### ISSUE TITLE
Add recent sermons to edit author page

### ISSUE THREAD

**Issue by monty5811** [FraserCoyle/sermon-manager-issues#63]
Display 10 most recent sermons in a table, with links to edit page, etc.

Should also have a toggle to only show sermons that the speaker has preached in my church.

**Comment by andrewmfraser** [comment]
Churches are completely isolated, you can't see data from another church in a view, you have to switch churches first.

Will add to the edit page though :+1:

**Comment by andrewmfraser** [comment]
Complete will be rolled out with UI1.0
