### ISSUE TITLE
Upload video bug

### ISSUE THREAD

**Issue by thealioli** [FraserCoyle/sermon-manager-issues#65]
See screenshot,

Not working in Chrome 45 or 44 but also tested in IE and not working there either.

Site reports that URL is not valid. Also tried with different forms of URL that YouTube provides but no joy.

![sermon manager bug 2015-06-19](https://cloud.githubusercontent.com/assets/8791163/8253737/6901f28e-168a-11e5-9a0b-e97cd4f84977.JPG)

**Comment by andrewmfraser** [comment]
Fixed, YouTube closed access to v2 of the API
