### ISSUE TITLE
Fix full chapter passage display

### ISSUE THREAD

**Issue by monty5811** [FraserCoyle/sermon-manager-issues#74]
![image](https://cloud.githubusercontent.com/assets/5426677/8765271/bc4b3660-2dfc-11e5-9c1e-8cdac7bd105f.png)

There are only 13 verses in the Psalm, so it should be "Psalm 96". That is how one would commonly write it and it makes it easier to see that the whole Psalm is the passage, without having to look up how many verses there are.

**Comment by andrewmfraser** [comment]
We will probably sort this in the UI Update (#33) as we need to overhaul passages input and display across the platform.
