### ISSUE TITLE
Avoid Mis-match of series images

### ISSUE THREAD

**Issue by JNaismith** [FraserCoyle/sermon-manager-issues#79]
I just noticed that there is a non-loading image for Bruntsfield's sermons in the Series "One Off Sermons". I've also noticed that a recent church has recently added a series with the same permalink with their own image. According to the database, the uploading of their image somehow affected the image used in Bruntsfield's sermons. I've fixed it for now, but tests need to be added to avoid this in future.

**Comment by andrewmfraser** [comment]
We need to make sure church_id is checked everywhere so that no clashes cross-church can occur.
